### ISSUE TITLE
[Issue]: Apply changes 3.0

### ISSUE THREAD

**Issue by StrangerGithuber** [an-anime-team/an-anime-game-launcher#1]
### Distro

Manjaro

### Installation Type

AUR

### Describe the issue

Hello
I get an error message:
"An error occurred during game updating"
"35 files couldn't be updated by the hdiff patch"

When clicking to the "Apply changes" button then starting loading something and appearing again the same button.

### Reproduction Steps

Installed long time ago the launcher and just clicked to the update in the "Add/Remove Software.

**Comment by Mar0xy** [comment]
This issue started happening with the 2.3.6 version of the launcher when 3.0.0 came out due to a change and was fixed in 2.3.8 so If updates were done prior to that release it would mess up causing this issue so far the only way to fix this is to reinstall the entire game.

Since you are using AUR all you need to do is run this command to remove the game
```bash
rm -rf ~/.local/share/anime-game-launcher/game
```

**Comment by c02y** [comment]
Will "re-apply patch" in `Settings` work? I cann't try it since I already delete the whole directory and redownload everything.
