### ISSUE TITLE
Apply patch error

### ISSUE THREAD

**Issue by slydeangel** [an-anime-team/an-anime-game-launcher#126]
Hello there, when i downloaded and updated the game, but when i click to apply the patch it says "failed to apply the patch".
what can i do to solve this ?
thank you

**Comment by c02y** [comment]
You can click the button error bar for the details.

In case you don't know, you have to edit the `~/.local/share/anime-game-launcher/patch/360/patch_anti_logincrash.sh` and `~/.local/share/anime-game-launcher/patch/360/patch.sh`, remove the first `exit` line in the two files since the patch is testing patch.


I already patched the Global edition, after I change the edition to China and trying to appy the CN patch, it failed.

Is it the same as yours?
![image](https://user-images.githubusercontent.com/2135996/231459154-63ac65e7-a651-44e0-9810-e13c70ccecfb.png)

**Comment by slydeangel** [comment]
i am in global edition , and there is no patch folder , that is weird. what can i do ?

**Comment by c02y** [comment]
Do you have to error bar at the bottom of the launcher window?

**Comment by slydeangel** [comment]
![WhatsApp Image 2023-04-12 at 14 52 06](https://user-images.githubusercontent.com/30873373/231463190-41f1bb40-4ded-4df6-a54c-84eef283dd55.jpeg)

**Comment by c02y** [comment]
Check the setting icon for the patch info.

If you don't mind, you can delete the `~/.local/share/anime-game-launcher` directory and redo the installation from the first beginning, not sure if can fix your issue, but you can give it a try.

**Comment by slydeangel** [comment]
yeah , i deleted.
i'm going to do everything from the beguining.
i'll tell something once its done.
 thanks :D

**Comment by krypt0nn** [comment]
Fixed in https://github.com/an-anime-team/an-anime-game-launcher/pull/127

**Comment by slydeangel** [comment]
still not working after that
