### ISSUE TITLE
Failed to update launcher state: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Nik--** [an-anime-team/an-anime-game-launcher#170]
After downloading the prefix, game and applying the patch, I get the following error:

```
Failed to update launcher state: No such file or directory (os error 2)
```

Currently running on Gentoo system, using the latest native build (3.7).

[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/11563120/debug.txt)

**Comment by YogSottot** [comment]
Make sure to disable the xlua patch, it does not exist yet

**Comment by Ruojo** [comment]
I have the same problem, even if I disabled the xlua patch

**Comment by Ruojo** [comment]
I have the same problem, even if I disabled the xlua patch

**Comment by Nik--** [comment]
> Make sure to disable the xlua patch, it does not exist yet

Yes, this did work. Thanks.
It would've been nice if the updater warned about which file exactly is missing. I searched in the logs, but didn't find a file.

**Comment by royalchevas** [comment]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/36443315/462e52c4-9b30-4f1d-a4da-8d7f3d99771f)
same problem

**Comment by krypt0nn** [comment]
For now just disable xlua patch in launcher settings. If it toasts "os error 2" on the launcher loading screen - then something's wrong with your game installation and you should run game repairer... which won't work as well on current launcher version due to *xlua patch issues* (this will be fixed in a few days once I release new update)
