### ISSUE TITLE
[Feature Request]: Distribute flatpakref file for easier install

### ISSUE THREAD

**Issue by Thesola10** [an-anime-team/an-anime-game-launcher#20]
### What the feature is suppose to do

A `.flatpakref` file contains a reference to a Flatpak on a repository, and allows for adding all required repositories in one go. The user experience of a `.flatpakref` is that it is opened by the app store (GNOME Software, Discover) as the "about page" for the application.

### Describe the reason behind the request

This is simpler than the commands listed, and would allow the flatpak to be listed in the Releases page.

Oh, I almost forgot: a flatpakref can contain a signing key, which makes installing the program safer.

**Comment by Thesola10** [comment]
Example `.flatpakref` for this app:

```ini
[Flatpak Ref]
Name=com.gitlab.KRypt0n_.an-anime-game-launcher
Branch=master
Title=An Anime Game Launcher
IsRuntime=false
Url=https://gol.launcher.moe/repo/
SuggestRemoteName=launcher.moe
GPGKey=xxxxx
RuntimeRepo=https://dl.flathub.org/repo/flathub.flatpakrepo
```

Notice the ability to specify a third-party runtime repo in the same file

**Comment by Mar0xy** [comment]
> a flatpakref can contain a signing key, which makes installing the program safer.
By default flatpakref files don't contain a signing key the key is provided by our repo itself
> as well as easy(ish) downgrade if needed.
This is false as the flatpakref pulls the info from the repo yet again so you still need to figure out stuff yourself to downgrade it.

Here is an example of the flatpakref for the GTK launcher that got generated

![image](https://user-images.githubusercontent.com/8841466/194819007-3bd83d37-38d2-46cf-9164-f083076d885f.png)


Overall this would have no benefit besides auto-adding flathub which makes this kind of redundant since no one has complained about this so far.

**Comment by Thesola10** [comment]
thought it was worth considering from a UX POV

> as well as easy(ish) downgrade if needed.

yeah i took that back soz
