### ISSUE TITLE
Failed to patch game: "Patch folder doesn't exist"

### ISSUE THREAD

**Issue by lsdxm** [an-anime-team/an-anime-game-launcher#200]
I'm on EndeavourOS, I've tried the launcher from the AUR and the flatpak and both fail to patch the game saying the folder (~/an-anime-game-launcher/patch/370/370) doesn't exist. If I create the folder it says "No such file or directory (os error 2)"

**Comment by krypt0nn** [comment]
This can be an issue with the latest update because I changed some inner stuff related to the game patching, and believed one user who said that everything works

Previous launcher version will apply the patch without issues. Or you can follow instructions from the patch repo and apply it yourself. Or you can wait for an update when I fix the issue and release new update

**Comment by krypt0nn** [comment]
Just tested it myself and approve that it's an issue on my side. Fix will be released today. Thanks for the report

Will keep this issue open for today

**Comment by krypt0nn** [comment]
Fixed in https://github.com/an-anime-team/an-anime-game-launcher/releases/tag/3.7.4. Closing

**Comment by lsdxm** [comment]
Thank yooooou ^_^
