### ISSUE TITLE
Confused about the checkbox effect in the Settings

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#204]
Confused about:
1. Is Button on the left the `Check`, or is button on the right the `Check`
2. Sometimes whenever the button is on the left or on the right, the color is always highlighted
3. After I reopen the Settings or reopen the launcher, the configuration is reset.

So I don't know what I've done or what I should do about the checkbox.

If you need any other info, please let me know.

https://github.com/an-anime-team/an-anime-game-launcher/assets/2135996/3c6740af-abf7-4cdd-9f13-c81cda2c7031

**Comment by krypt0nn** [comment]
GTK bug. Look at color, not at position

**Comment by c02y** [comment]
So it means, when I click the checkbox, sometimes the color is not changed as you can see in the video, it means I have to click it again until the color is changed no matter where the button is to get the toggle effect.

**Comment by Caliel666** [comment]
the bug is that it's actually toggled on, but the button is in the wrong position, so you need to click again to put it in the correct position and one more time to toggle it off, so follow the color, not the position

https://github.com/an-anime-team/an-anime-game-launcher/assets/38433434/cfd44f54-9598-40e7-90dc-8c12545c2028

*this happens in a bunch of GTK apps, it's a bug they need to fix, not this app
