### ISSUE TITLE
[Issue]: Disk out of space issue when unpacking the game data

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#25]
### Distro

Arch Linux

### Installation Type

AUR

### Describe the issue

When I download the game in the launcher, if the disk is out of space during the unpacking process, it gets stuck without extra info, so I notice the disk is out of space and clean some files, and resume, the launcher will not resume, I kill the launcher and reopen it, it downloads the audio data directly (click the `Update` button) without unpacking the game zip file, if the disk is out of space again during unpacking the audio zip file, the issue will happen again.

**Comment by Mar0xy** [comment]
This happens due to this version of the launcher not checking for disk space. the [GTK](https://github.com/an-anime-team/an-anime-game-launcher-gtk) version does check for disk space so if you need that then I recommend switching over as this version only gets bug fixes and few minor new features but nothing major.

**Comment by c02y** [comment]
Thanks, so this version will be deprecated in some time?
