### ISSUE TITLE
[Feature Request]: IE patch about BiliBili channel

### ISSUE THREAD

**Issue by QiE2035** [an-anime-team/an-anime-game-launcher#4]
### What the feature is suppose to do

**[Tanslated by Google]**
I made a patch (https://github.com/QiE2035/gs_bili) to require IE when logging into the BiliBili channel, hoping to make it part of the launcher.

### Describe the reason behind the request

**[Tanslated by Google]**
In China, the game is divided into miHoYo (internationally called HoYoverse) channel and BiliBili channel, I am a player of BiliBili channel, Krock's patch has provided a patch for this channel since version 2.7, but since the BiliBili channel is used when logging in IE browser, and Wine's Gecko can not meet the requirements, also difficult to install the correct and running version of IE (IE9+) so I made this suggested patch to bypass IE restrictions, I hope the patch I made will have a chance To help more Linux users and BiliBili channel players as part of this launcher.

**Comment by Mar0xy** [comment]
Thanks for the request,

This does sound interesting but due to limitations like configure the required patch manually by visiting a URL and then changing editing a JSON file this makes it complicated to implement especially since there is no way to actually check if it has been edited or if someone is using the BiliBili server.

Another issue occurs when we come to the downloading part since there is no easy way to download the patch(like a release with all required files in one zip) this complicates the way of adding it as an option.

The last issue is no one is able to test it on the team since no one is Chinese nor has access to a Chinese account to test if it works.

As such this will be marked as not planned but you can go ahead and try adding it yourself and submitting a PR as this is the beauty of open source projects.
