### ISSUE TITLE
Loading stopped at 100% (16.41GB of 16.41GB) Ubuntu 24.04

### ISSUE THREAD

**Issue by Keqy** [an-anime-team/an-anime-game-launcher#407]
![изображение](https://github.com/user-attachments/assets/0bdb4d6e-2a3e-4a5b-8506-2c73d648df35)

It's been stuck at 100% for an hour now. I tried restarting the computer and the launcher, but it doesn't help.

**Comment by FelixSiegel** [comment]
Same for me on the Steam Deck here. Because this is very annoying, I have done some research into the file structure and found a workaround that fixes the error for me.

First, if you open the game folder, you will notice the English language package, which has a size of exactly 16.41 GB (due to the human-readable output flag (`-h`), it is shown as 17 GB):

![1](https://github.com/user-attachments/assets/9689a042-7da3-4857-b611-98fdcb6f59bd)

I then found the Game Voiceovers tab in the settings:

![2](https://github.com/user-attachments/assets/706fa95e-eea4-4101-a702-0ccb17b3d612)

If you expand the section, you should see English marked as downloaded. Simply click on "Remove." 

![3](https://github.com/user-attachments/assets/84941bdc-b242-4dba-ad2c-d3f3d1d72e7e)

This won't delete the file in the directory, but it resolves the error. I don't know if selecting another language package will also solve it (my internet is very slow, so I haven't tested it), but for me, it worked fine. The game runs without any crashes. Also, I'm not sure if you can remove the language package completely (remember that clicking "Remove" in the launcher settings doesn't actually remove it) or if this will lead to in-game errors.

Let me know if this works for you too, or if you have resolved the uncertainties in my comment.

**Comment by Keqy** [comment]
Thank you a lot. Anyway, i'm just reinstall all the game with launcher. Now it works. The launcher gets stuck here for a long time, but that's ok.

**Comment by jamieernest** [comment]
Same issue for me (steam deck), same steps solved it, but instead of only English you have to delete the English one first, then it will get stuck on Japanese, you'll have to delete Japanese, and so on. But the game seems to just redownload them on launch so it's mostly fine, just an annoyance

**Comment by jamieernest** [comment]
@Keqy has this been fixed?

**Comment by Keqy** [comment]
@jamieernest 
It loaded itself
