### ISSUE TITLE
an anime game launcher" telemetry servers are not disabled" [Issue]: 

### ISSUE THREAD

**Issue by ds47x** [an-anime-team/an-anime-game-launcher#43]
### Distro

i just installed the game and tried it and it came with that error.

i use OS: Manjaro Linux x86_64
         Host: Inspiron 15-3567
         CPU: Intel i3-7130U (4) @ 2.700GHz with 8gb ram

### Installation Type

AUR

### Describe the issue

idk how to describe it it just happened

**Comment by mowohre** [comment]
i have got the same error. 
my OS is Manjaro Linux x86_64 too, maybe it has something to do with that?

**Comment by ds47x** [comment]
> i have got the same error. 
> my OS is Manjaro Linux x86_64 too, maybe it has something to do with that?
> 
> 

I got the solution...just locate the game exe in home/.local/an animal game launcher/.......I'm not sure exactly where it is but just locate the genshin impact exe and add it to lutris directly. It worked for me

**Comment by Mar0xy** [comment]
telemetry servers are not disabled happens when the patch hasn't patched the telemetry servers which shares data to the devs about your system. this is a safety check. if it pops up then this generally means that you are missing polkit and a polkit gui that asks for root/admin to patch your hosts file. Please refer to our Discord in this case to get answers as we can't share the urls here.

**Comment by ds47x** [comment]
> telemetry servers are not disabled happens when the patch hasn't patched the telemetry servers which shares data to the devs about your system. this is a safety check. if it pops up then this generally means that you are missing polkit and a polkit gui that asks for root/admin to patch your hosts file. Please refer to our Discord in this case to get answers.

Thanks men
