### ISSUE TITLE
[Issue]: Controller problem on Steam deck 

### ISSUE THREAD

**Issue by rootmelo92118** [an-anime-team/an-anime-game-launcher#62]
### Distro

Steam deck OS 3.0

### Installation Type

Flatpak

### Describe the issue

I install `an-anime-game-launcher` in my steam deck. When I switch the control type from the keyboard to the controller, I can not operate the game, even though I can not change it back to the keyboard. I do not know how to solve this kind of problem.

**Comment by chronospectrum** [comment]
Does changing the controller settings in Steam to the Gamepad With Joystick Trackpad template allow you to interact with the game again?

**Comment by rootmelo92118** [comment]
> Does changing the controller settings in Steam to the Gamepad With Joystick Trackpad template allow you to interact with the game again?

How to do that?

**Comment by chronospectrum** [comment]
1. Start the game as normal
2. press the Steam button to bring up the overlay
3. Navigate to the Controller Settings page (just between Resume Game and View Game Details)
4. Press Controller Settings at the bottom of the page
5. At the top, select the current layout to browse a list of control templates and community layouts. For testing purposes, try to use the Gamepad with Mouse Trackpad option in the templates list.
6. Press X to apply the layout
7. Close the overlay by pressing the Steam menu. You should now be able to interact with the game. Note that the title screen of the game may still require a mouse click to interact with it. To do this, use the right trackpad or tap the screen

I would strongly recommend looking at the Steam Deck subreddit for more information about using the steam deck, as this issue isn't really caused by the anime game launcher

**Comment by rootmelo92118** [comment]
It works! Thanks you.
