### ISSUE TITLE
Add game edition switcher

### ISSUE THREAD

**Issue by krypt0nn** [an-anime-team/an-anime-game-launcher#97]
Some people from China say that they have accounts on both game editions. This change will allow them to easily switch game edition from settings

**Comment by c02y** [comment]
I have two accounts on both servers(China server and Asia Server), I wrote a desktop/bash-script file that,  when I open the desktop file, it popups a window using zenity to let me choose which server of the game to launch.

So basically I keep two folds of the two edtions in my disk, one is China server and the other is Global server:
- `~/.local/share/anime-game-launcher` and `~/.local/share/anime-game-launcher.cn`
or
- `~/.local/share/anime-game-launcher` and `~/.local/share/anime-game-launcher.global`

When I choose one server from the zenity window, it will check the names of the two folds and rename the folds if necessary and then launch the game.

I know this is a stupid solution, since I have to keep two game data in my disk which is over 100GB in total,

Really glad to see that I can choose editions from the launcher itself, although I have no idea how it will be implemented, hoping that I don't have to keep two completed game data in two folders.

**Comment by krypt0nn** [comment]
Unfortunately, you will have to
